# Generated by Django 5.2.12 on 2026-03-11 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("template", models.CharField(max_length=120)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("processing", "processing"),
                            ("sent", "sent"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("manual_review", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "email_outbox",
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="outbox_status_created_idx"),
                    models.Index(fields=["to_email"], name="outbox_to_email_idx"),
                    models.Index(fields=["sent_at"], name="outbox_sent_at_idx"),
                ],
            },
        ),
    ]
