# Generated by Django 5.2.12 on 2026-03-11 14:30
# core/migrations/0001_db_extensions.py
from django.db import migrations

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE EXTENSION IF NOT EXISTS pgcrypto;
            CREATE EXTENSION IF NOT EXISTS btree_gist;

            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'booking_status') THEN
                    CREATE TYPE booking_status AS ENUM ('confirmed', 'cancelled');
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'workflow_status') THEN
                    CREATE TYPE workflow_status AS ENUM ('new', 'contacted', 'confirmed', 'paid', 'completed', 'cancelled');
                END IF;
            END$$;
            """,
            reverse_sql="""
            DROP TYPE IF EXISTS workflow_status;
            DROP TYPE IF EXISTS booking_status;
            DROP EXTENSION IF EXISTS btree_gist;
            DROP EXTENSION IF EXISTS pgcrypto;
            """,
        ),
    ]
