# Generated by Django 5.2.12 on 2026-03-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_db_extensions"),
        ("core", "0002_uuid_defaults"),
    ]

    operations = []
