# Generated by Django 5.2.12 on 2026-03-11 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=255, unique=True)),
                ("url", models.URLField(max_length=500)),
                ("size", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                ("published", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "uploads",
            },
        ),
    ]
