# Generated by Django 5.2.12 on 2026-03-11 14:35
# bookings/migrations/0001_confirmed_ranges.py
from django.db import migrations

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_db_extensions"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS bookings_confirmed_ranges (
                booking_id uuid PRIMARY KEY,
                event_range tstzrange NOT NULL
            );

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'bookings_confirmed_ranges_no_overlap'
                ) THEN
                    ALTER TABLE bookings_confirmed_ranges
                    ADD CONSTRAINT bookings_confirmed_ranges_no_overlap
                    EXCLUDE USING gist (event_range WITH &&);
                END IF;
            END$$;
            """,
            reverse_sql="""
            ALTER TABLE IF EXISTS bookings_confirmed_ranges
            DROP CONSTRAINT IF EXISTS bookings_confirmed_ranges_no_overlap;
            DROP TABLE IF EXISTS bookings_confirmed_ranges;
            """,
        ),
    ]
