# Generated by Django 5.2.12 on 2026-03-11 15:20

import core.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_confirmed_ranges"),
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer_name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
                ("event_type", models.CharField(max_length=120)),
                ("event_date_start", models.DateTimeField()),
                ("event_date_end", models.DateTimeField()),
                ("event_all_day", models.BooleanField(default=False)),
                (
                    "guests",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("dietary_needs", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    core.fields.PostgresEnumField(
                        choices=[
                            ("confirmed", "confirmed"),
                            ("cancelled", "cancelled"),
                        ],
                        default="confirmed",
                        enum_name="booking_status",
                        max_length=20,
                    ),
                ),
                (
                    "workflow_status",
                    core.fields.PostgresEnumField(
                        choices=[
                            ("new", "new"),
                            ("contacted", "contacted"),
                            ("confirmed", "confirmed"),
                            ("paid", "paid"),
                            ("completed", "completed"),
                            ("cancelled", "cancelled"),
                        ],
                        default="new",
                        enum_name="workflow_status",
                        max_length=20,
                    ),
                ),
                ("deposit_paid", models.BooleanField(default=False)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="packages.package",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
                "indexes": [
                    models.Index(
                        fields=["event_date_start"], name="bookings_event_d_5857d5_idx"
                    ),
                    models.Index(
                        fields=["event_date_end"], name="bookings_event_d_13e156_idx"
                    ),
                    models.Index(
                        fields=["workflow_status"], name="bookings_workflo_16164f_idx"
                    ),
                ],
            },
        ),
    ]
