# Generated by Django 5.2.12 on 2026-03-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("request_hash", models.CharField(max_length=64)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_headers", models.JSONField(blank=True, null=True)),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "idempotency_keys",
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="idx_idempotency_expires_at"
                    )
                ],
            },
        ),
    ]
